"""create_phase3_user_and_role_tables

Revision ID: 56635abf39f0
Revises: b84657b131fa
Create Date: 2026-10-01 11:21:38.086558+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56635abf39f0'
down_revision: Union[str, None] = 'b84657b131fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user',
    sa.Column('UserId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserName', sa.String(length=255), nullable=True),
    sa.Column('UserPassword', sa.String(length=255), nullable=True),
    sa.Column('UserRoleId', sa.Integer(), nullable=True),
    sa.Column('BranchId', sa.Integer(), nullable=True),
    sa.Column('isappuser', sa.String(length=255), nullable=True),
    sa.Column('isdeleted', sa.String(length=255), nullable=True),
    sa.Column('CreateDate', sa.DateTime(), nullable=True),
    sa.Column('CreateUser', sa.String(length=255), nullable=True),
    sa.Column('UpdateDate', sa.DateTime(), nullable=True),
    sa.Column('UpdateUser', sa.String(length=255), nullable=True),
    sa.Column('partner_user_id', sa.String(length=250), nullable=True),
    sa.Column('mobile_no', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('UserId'),
    sa.UniqueConstraint('UserName'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('fk_BranchId', 'tbl_user', ['BranchId'], unique=False)
    op.create_index('fk_UserRoleId', 'tbl_user', ['UserRoleId'], unique=False)
    op.create_table('tbl_userrole',
    sa.Column('UserRoleId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserRole', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('isdeleted', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('UserRoleId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_row_format='DYNAMIC'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_userrole')
    op.drop_index('fk_UserRoleId', table_name='tbl_user')
    op.drop_index('fk_BranchId', table_name='tbl_user')
    op.drop_table('tbl_user')
    # ### end Alembic commands ###
