"""add_customer_indexes

Revision ID: 6502a09489d3
Revises: cfb1bd63a8ff
Create Date: 2026-10-05 11:51:27.955189+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6502a09489d3'
down_revision: Union[str, None] = 'cfb1bd63a8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('CustomerCode_UNIQUE', 'tbl_customer', ['CustomerCode'], unique=True, mysql_length=100)
    op.create_index('Fk18_BranchId_idx', 'tbl_customer', ['BranchId'], unique=False)
    op.create_index('Fk5_ClientId_idx', 'tbl_customer', ['ClientId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Fk5_ClientId_idx', table_name='tbl_customer')
    op.drop_index('Fk18_BranchId_idx', table_name='tbl_customer')
    op.drop_index('CustomerCode_UNIQUE', table_name='tbl_customer', mysql_length=100)
    # ### end Alembic commands ###
