"""create_phase6_quotation_rating_tables

Revision ID: 7bfd3202dcf7
Revises: 6502a09489d3
Create Date: 2026-10-06 09:05:04.899871+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7bfd3202dcf7'
down_revision: Union[str, None] = '6502a09489d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_addonextraamt',
    sa.Column('ExtraAddonId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('InsuranceCompanyId', sa.Integer(), nullable=True),
    sa.Column('VehiceTypeId', sa.Integer(), nullable=True),
    sa.Column('makeId', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('ModelId', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('Age', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('NillDep', sa.Double(), nullable=True),
    sa.Column('SecurePlus', sa.Double(), nullable=True),
    sa.Column('SPremium', sa.Double(), nullable=True),
    sa.Column('No', sa.Double(), nullable=True),
    sa.Column('IsDeleted', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('ExtraAddonId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_app_bus_cc_rate',
    sa.Column('BUSCC_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Bus_Type', sa.String(length=255), nullable=True),
    sa.Column('Veh_Type_ID', sa.Integer(), nullable=True),
    sa.Column('TP_Rate', sa.Double(), nullable=True),
    sa.Column('Veh_BasicRate', sa.Double(), nullable=True),
    sa.Column('Per_PassengerRate', sa.Double(), nullable=True),
    sa.Column('ODDiscount', sa.Double(), nullable=True),
    sa.Column('CreatedUser', sa.String(length=255), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('UpdatedUser', sa.String(length=255), nullable=True),
    sa.Column('UpdatedDate', sa.DateTime(), nullable=True),
    sa.Column('isdeleted', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('BUSCC_Id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_app_oddiscountnew',
    sa.Column('AppODDiscountId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Model_ID', sa.Integer(), nullable=True),
    sa.Column('MakeID', sa.Integer(), nullable=True),
    sa.Column('InsuranceCompanyId', sa.Integer(), nullable=True),
    sa.Column('Decline', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('Fueltypeid', sa.Integer(), nullable=True),
    sa.Column('BusinessTypeId', sa.Integer(), nullable=True),
    sa.Column('NCB', sa.String(length=255), nullable=True),
    sa.Column('ClusterId', sa.Integer(), nullable=True),
    sa.Column('ZeroDep', sa.String(length=255), nullable=True),
    sa.Column('PRVDetails', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('N', sa.String(length=255), nullable=True),
    sa.Column('Zero', sa.String(length=255), nullable=True),
    sa.Column('One', sa.String(length=255), nullable=True),
    sa.Column('Two', sa.String(length=255), nullable=True),
    sa.Column('Three', sa.String(length=255), nullable=True),
    sa.Column('Four', sa.String(length=255), nullable=True),
    sa.Column('Five', sa.String(length=255), nullable=True),
    sa.Column('Six', sa.String(length=255), nullable=True),
    sa.Column('Seven', sa.String(length=255), nullable=True),
    sa.Column('Eight', sa.String(length=255), nullable=True),
    sa.Column('Nine', sa.String(length=255), nullable=True),
    sa.Column('Ten', sa.String(length=255), nullable=True),
    sa.Column('Eleven', sa.String(length=255), nullable=True),
    sa.Column('Twelve', sa.String(length=255), nullable=True),
    sa.Column('thriteen', sa.String(length=255), nullable=True),
    sa.Column('fourteen', sa.String(length=255), nullable=True),
    sa.Column('fifteen', sa.String(length=255), nullable=True),
    sa.Column('Sixteen', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('AppODDiscountId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_app_oddiscountnew_gcv',
    sa.Column('AppODDiscountId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Model_ID', sa.Integer(), nullable=True),
    sa.Column('MakeID', sa.Integer(), nullable=True),
    sa.Column('InsuranceCompanyId', sa.Integer(), nullable=True),
    sa.Column('Fueltypeid', sa.Integer(), nullable=True),
    sa.Column('BusinessTypeId', sa.Integer(), nullable=True),
    sa.Column('NCB', sa.String(length=255), nullable=True),
    sa.Column('ClusterId', sa.Integer(), nullable=True),
    sa.Column('ZeroDep', sa.String(length=255), nullable=True),
    sa.Column('N', sa.String(length=255), nullable=True),
    sa.Column('Zero', sa.String(length=255), nullable=True),
    sa.Column('One', sa.String(length=255), nullable=True),
    sa.Column('Two', sa.String(length=255), nullable=True),
    sa.Column('Three', sa.String(length=255), nullable=True),
    sa.Column('Four', sa.String(length=255), nullable=True),
    sa.Column('Five', sa.String(length=255), nullable=True),
    sa.Column('Six', sa.String(length=255), nullable=True),
    sa.Column('Seven', sa.String(length=255), nullable=True),
    sa.Column('Eight', sa.String(length=255), nullable=True),
    sa.Column('Nine', sa.String(length=255), nullable=True),
    sa.Column('Ten', sa.String(length=255), nullable=True),
    sa.Column('Eleven', sa.String(length=255), nullable=True),
    sa.Column('Twelve', sa.String(length=255), nullable=True),
    sa.Column('thriteen', sa.String(length=255), nullable=True),
    sa.Column('fourteen', sa.String(length=255), nullable=True),
    sa.Column('fifteen', sa.String(length=255), nullable=True),
    sa.Column('Sixteen', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('AppODDiscountId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_app_pcv_cc_rate',
    sa.Column('PCVCC_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Veh_Type_ID', sa.Integer(), nullable=True),
    sa.Column('Up_CC', sa.Double(), nullable=True),
    sa.Column('To_CC', sa.Double(), nullable=True),
    sa.Column('TP_Rate', sa.Double(), nullable=True),
    sa.Column('Veh_BasicRate', sa.Double(), nullable=True),
    sa.Column('Per_PassengerRate', sa.Double(), nullable=True),
    sa.Column('CreatedUser', sa.String(length=255), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('UpdatedUser', sa.String(length=255), nullable=True),
    sa.Column('UpdatedDate', sa.DateTime(), nullable=True),
    sa.Column('isdeleted', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('PCVCC_Id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_app_quatationentry',
    sa.Column('QuatationId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('QuatationCode', sa.String(length=255), nullable=True),
    sa.Column('QuatationDate', sa.DateTime(), nullable=True),
    sa.Column('ProductName', sa.String(length=255), nullable=True),
    sa.Column('Title', sa.String(length=1000), nullable=True),
    sa.Column('MgfYear', sa.String(length=255), nullable=True),
    sa.Column('RTOId', sa.Integer(), nullable=True),
    sa.Column('Zone', sa.String(length=255), nullable=True),
    sa.Column('InsuranceCompanyId', sa.Integer(), nullable=True),
    sa.Column('Veh_Type_ID', sa.Integer(), nullable=True),
    sa.Column('Veh_Sub_Type_ID', sa.Integer(), nullable=True),
    sa.Column('Make_ID', sa.Integer(), nullable=True),
    sa.Column('Model_ID', sa.Integer(), nullable=True),
    sa.Column('Variant_ID', sa.Integer(), nullable=True),
    sa.Column('SeatsCapacity', sa.String(length=255), nullable=True),
    sa.Column('CubicCapacity', sa.String(length=255), nullable=True),
    sa.Column('VehicleWeight', sa.String(length=255), nullable=True),
    sa.Column('IDV', sa.String(length=255), nullable=True),
    sa.Column('OwnDamagePremium', sa.String(length=255), nullable=True),
    sa.Column('OD', sa.String(length=255), nullable=True),
    sa.Column('AddExtra15IMTno23', sa.String(length=255), nullable=True),
    sa.Column('ZeroDepreciation', sa.String(length=255), nullable=True),
    sa.Column('NoClaimBonus', sa.String(length=255), nullable=True),
    sa.Column('AddLoading', sa.String(length=255), nullable=True),
    sa.Column('AddPremiumAbove12000kg', sa.String(length=255), nullable=True),
    sa.Column('EletricAccessories', sa.String(length=255), nullable=True),
    sa.Column('CNGFulekits', sa.String(length=255), nullable=True),
    sa.Column('VehicleBasicRate', sa.String(length=255), nullable=True),
    sa.Column('BasicPremium', sa.String(length=255), nullable=True),
    sa.Column('LiabilityPremium', sa.String(length=255), nullable=True),
    sa.Column('TPRisk', sa.String(length=255), nullable=True),
    sa.Column('CNGfuleKitLiabilityPremium', sa.String(length=255), nullable=True),
    sa.Column('PAforOwnerDriver', sa.String(length=255), nullable=True),
    sa.Column('PAtoUnnamedocc', sa.String(length=255), nullable=True),
    sa.Column('LegallibtoEmp', sa.String(length=255), nullable=True),
    sa.Column('legallibtoPaidDriver', sa.String(length=255), nullable=True),
    sa.Column('TPPDLimtoRS6000', sa.String(length=255), nullable=True),
    sa.Column('PAToPaidDriver', sa.String(length=255), nullable=True),
    sa.Column('Antitheftacc', sa.String(length=255), nullable=True),
    sa.Column('Automobaccmemdis', sa.String(length=255), nullable=True),
    sa.Column('LLtoDrCleanerandCoolies', sa.String(length=255), nullable=True),
    sa.Column('LLtoNonfarepayingpass', sa.String(length=255), nullable=True),
    sa.Column('PABenefits', sa.String(length=255), nullable=True),
    sa.Column('PAtoPillionRider', sa.String(length=255), nullable=True),
    sa.Column('AtotalOwnDamPremium', sa.String(length=255), nullable=True),
    sa.Column('BtotalLiabilityPremium', sa.String(length=255), nullable=True),
    sa.Column('TotalPremium', sa.String(length=255), nullable=True),
    sa.Column('GST18', sa.String(length=255), nullable=True),
    sa.Column('finalPrmium', sa.String(length=255), nullable=True),
    sa.Column('AgentId', sa.Integer(), nullable=True),
    sa.Column('SaleExId', sa.Integer(), nullable=True),
    sa.Column('isdeleted', sa.String(length=255), server_default=sa.text("'0'"), nullable=True),
    sa.Column('NCBPre', sa.String(length=255), server_default=sa.text("'0'"), nullable=False),
    sa.Column('FuelTypeId', sa.Integer(), nullable=True),
    sa.Column('UserRoleId', sa.Integer(), nullable=True),
    sa.Column('BodyPrice', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.Column('ChassisPrice', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.Column('Mfg_Year', sa.DateTime(), nullable=True),
    sa.Column('RegistrationNo', sa.String(length=255), nullable=True),
    sa.Column('ProductType', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('QuatationId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_index('Title', 'tbl_app_quatationentry', ['Title'], unique=True, mysql_length=200)
    op.create_table('tbl_app_quotationremark',
    sa.Column('QuatRemarkId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('QuatationId', sa.Integer(), nullable=True),
    sa.Column('QuatationDate', sa.DateTime(), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('Remark', sa.String(length=500), nullable=True),
    sa.Column('UpdateBy', sa.String(length=200), nullable=True),
    sa.Column('UpdateDate', sa.DateTime(), nullable=True),
    sa.Column('isdeleted', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('RemarkFrom', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('QuatRemarkId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_app_quotationrequest',
    sa.Column('QuatationId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('QuatationDate', sa.DateTime(), nullable=True),
    sa.Column('InsuranceCompanyId', sa.String(length=255), nullable=True),
    sa.Column('VehicleId', sa.Integer(), nullable=True),
    sa.Column('AgentId', sa.Integer(), nullable=True),
    sa.Column('QuotationFile', sa.String(length=1000), nullable=True),
    sa.Column('ProductType', sa.String(length=255), nullable=True),
    sa.Column('Zerodepth', sa.String(length=255), nullable=True),
    sa.Column('PolicyMode', sa.String(length=255), nullable=True),
    sa.Column('MobileNo', sa.String(length=255), nullable=True),
    sa.Column('NCB', sa.String(length=255), nullable=True),
    sa.Column('PolicyImage', sa.String(length=1000), nullable=True),
    sa.Column('IsQuotationGenerate', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('VehicleNo', sa.String(length=255), nullable=True),
    sa.Column('Camera', sa.String(length=1000), server_default=sa.text("''"), nullable=False),
    sa.Column('UserRoleId', sa.Integer(), nullable=True),
    sa.Column('SalesEx_Id', sa.Integer(), nullable=True),
    sa.Column('OtherAgentName', sa.String(length=255), nullable=True),
    sa.Column('VehicleType', sa.String(length=255), nullable=True),
    sa.Column('VehicleMake', sa.String(length=255), nullable=True),
    sa.Column('VehicleModel', sa.String(length=255), nullable=True),
    sa.Column('VehicleVariance', sa.String(length=255), nullable=True),
    sa.Column('policytype', sa.String(length=255), nullable=True),
    sa.Column('FlagForPopup', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('updatedDate', sa.DateTime(), nullable=True),
    sa.Column('LocationHeadId', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('QuatationCode', sa.String(length=500), nullable=True),
    sa.Column('ReadStatus', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('Note', sa.String(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('isdeleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('FranchiseId', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('Remark', sa.String(length=500), nullable=True),
    sa.Column('UpdateBy', sa.String(length=200), nullable=True),
    sa.Column('isPendingRevert', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('CancelRemark', sa.String(length=500), nullable=True),
    sa.Column('CancelDate', sa.DateTime(), nullable=True),
    sa.Column('CancelBy', sa.String(length=100), nullable=True),
    sa.Column('AttendedBy', sa.String(length=100), nullable=True),
    sa.Column('AttendedDate', sa.DateTime(), nullable=True),
    sa.Column('QuotSendDate', sa.DateTime(), nullable=True),
    sa.Column('AttendedUserId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('QuatationId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_app_requestedquotationfile',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('QuotationId', sa.Integer(), nullable=True),
    sa.Column('CompanyId', sa.Integer(), nullable=True),
    sa.Column('File_Name', sa.String(length=255), nullable=True),
    sa.Column('FilePath', sa.String(length=500), nullable=True),
    sa.Column('IsDelete', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('CreatedDate', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_app_threewheeler_cc_rate',
    sa.Column('ThreeWheelerCC_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UpAge', sa.Integer(), nullable=True),
    sa.Column('ToAge', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ThreeWheeler_Type', sa.String(length=255), nullable=True),
    sa.Column('Veh_Type_ID', sa.Integer(), nullable=True),
    sa.Column('TP_Rate', sa.Double(), nullable=True),
    sa.Column('Veh_BasicRate', sa.Double(), nullable=True),
    sa.Column('Per_PassengerRate', sa.Double(), nullable=True),
    sa.Column('CreatedUser', sa.String(length=255), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('UpdatedUser', sa.String(length=255), nullable=True),
    sa.Column('UpdatedDate', sa.DateTime(), nullable=True),
    sa.Column('isdeleted', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('ThreeWheelerCC_Id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_app_twowheelercc_rate',
    sa.Column('CC_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Veh_Type_ID', sa.Integer(), nullable=True),
    sa.Column('Up_CC', sa.Double(), nullable=True),
    sa.Column('To_CC', sa.Double(), nullable=True),
    sa.Column('TP_Rate', sa.Double(), nullable=True),
    sa.Column('Veh_BasicRate', sa.Double(), nullable=True),
    sa.Column('CreatedUser', sa.String(length=255), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('UpdatedUser', sa.String(length=255), nullable=True),
    sa.Column('UpdatedDate', sa.DateTime(), nullable=True),
    sa.Column('isdeleted', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('CC_Id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_appoddiscount',
    sa.Column('AppODDiscount', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Make_ID', sa.Integer(), nullable=True),
    sa.Column('Model_ID', sa.Integer(), nullable=True),
    sa.Column('InsuranceCompanyId', sa.Integer(), nullable=True),
    sa.Column('NewVehicle', sa.String(length=255), nullable=True),
    sa.Column('ZerotoFive', sa.String(length=255), nullable=True),
    sa.Column('fivetoTen', sa.String(length=255), nullable=True),
    sa.Column('Greaterthen10', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('AppODDiscount'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_index('tbl_insurancecompany', 'tbl_appoddiscount', ['InsuranceCompanyId'], unique=False)
    op.create_index('tbl_vehicle_make', 'tbl_appoddiscount', ['Make_ID'], unique=False)
    op.create_index('tbl_vehicle_model', 'tbl_appoddiscount', ['Model_ID'], unique=False)
    op.create_table('tbl_insurancecompanybyvehicletype',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('InsuranceCompanyId', sa.Integer(), nullable=True),
    sa.Column('GCV', sa.Integer(), nullable=True),
    sa.Column('GCV_Disc', sa.Double(), nullable=True),
    sa.Column('Misc_D', sa.Integer(), nullable=True),
    sa.Column('Misc_D_Disc', sa.Double(), nullable=True),
    sa.Column('PCV', sa.Integer(), nullable=True),
    sa.Column('PCV_Disc', sa.Double(), nullable=True),
    sa.Column('PVT_CAR', sa.Integer(), nullable=True),
    sa.Column('PVT_CAR_Disc', sa.Double(), nullable=True),
    sa.Column('Two_Wheeler', sa.Integer(), nullable=True),
    sa.Column('Two_Wheeler_Disc', sa.Double(), nullable=True),
    sa.Column('Bus', sa.Integer(), nullable=True),
    sa.Column('Bus_Disc', sa.Double(), nullable=True),
    sa.Column('Three_Wheeler', sa.Integer(), nullable=True),
    sa.Column('Three_Wheeler_Disc', sa.Double(), nullable=True),
    sa.Column('IsDelete', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('Extra', sa.String(length=255), nullable=True),
    sa.Column('Three_Wheeler_PCV', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('Three_Wheeler_PCV_Disc', sa.Double(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_insurancecompanyquotation',
    sa.Column('QuotationId', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('InsuranceCompanyId', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('TransctionId', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('agentId', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('QuotationFile', sa.String(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('EmpId', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('isdeleted', sa.String(length=255), server_default=sa.text("'0'"), nullable=False),
    sa.Column('InsertDate', sa.DateTime(), nullable=True),
    sa.Column('Remark', sa.String(length=255), nullable=True),
    sa.Column('Quotationfile_Name', sa.String(length=255), nullable=True),
    sa.Column('ProductId', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('QuotationId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_insurancecompanywisetowingchanges',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('InsuranceCompanyId', sa.Integer(), nullable=True),
    sa.Column('Selection', sa.Double(), nullable=True),
    sa.Column('Rate', sa.Double(), nullable=True),
    sa.Column('GST18', sa.Double(), nullable=True),
    sa.Column('Total', sa.Double(), nullable=True),
    sa.Column('IsDelete', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('Flag', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_patoownerdriver',
    sa.Column('PAToOwnerDriverId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('InsuranceCompanyId', sa.Integer(), nullable=True),
    sa.Column('Rate', sa.Double(), nullable=True),
    sa.Column('TowingCharges', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.Column('IsDeleted', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('PAToOwnerDriverId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_quot_damagepremium',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Company_Id', sa.Integer(), nullable=True),
    sa.Column('Company_Type', sa.String(length=45), nullable=True),
    sa.Column('fromCubicCapacity', sa.Integer(), nullable=True),
    sa.Column('toCubicCapacity', sa.Integer(), nullable=True),
    sa.Column('Age', sa.Double(), nullable=True),
    sa.Column('OD_premium_Azone', sa.Double(), nullable=True),
    sa.Column('OD_premium_Bzone', sa.Double(), nullable=True),
    sa.Column('OD_premium_Czone', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_quot_liabilitypremium',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Company_Id', sa.Integer(), nullable=True),
    sa.Column('Company_Type', sa.String(length=45), nullable=True),
    sa.Column('UNIT', sa.String(length=45), nullable=True),
    sa.Column('fromunit', sa.Integer(), nullable=True),
    sa.Column('tounit', sa.Integer(), nullable=True),
    sa.Column('Premium', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_quotation_prefix',
    sa.Column('Id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Code', sa.String(length=255), nullable=False),
    sa.Column('CodeLength', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('IsDeleted', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('UserRoleId', sa.Integer(), nullable=True),
    sa.Column('NoOfDigit', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_selfdiscount',
    sa.Column('SelfDiscId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BranchId', sa.Integer(), nullable=True),
    sa.Column('ReferenceType', sa.String(length=255), nullable=True),
    sa.Column('SelfDiscount', sa.Double(), nullable=True),
    sa.Column('ValidFrom', sa.DateTime(), nullable=True),
    sa.Column('BrokerId', sa.Integer(), nullable=True),
    sa.Column('IsDelete', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('CreatedUser', sa.String(length=255), nullable=True),
    sa.Column('UpdatedDate', sa.DateTime(), nullable=True),
    sa.Column('UpdatedUser', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('SelfDiscId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_zerodep',
    sa.Column('ZerodepId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('InsuranceCompanyId', sa.Integer(), nullable=True),
    sa.Column('Make_ID', sa.Integer(), nullable=True),
    sa.Column('Type', sa.Integer(), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('NillDep', sa.String(length=255), nullable=True),
    sa.Column('SecurePlus', sa.String(length=255), nullable=True),
    sa.Column('SPremium', sa.String(length=255), nullable=True),
    sa.Column('NO', sa.String(length=255), nullable=True),
    sa.Column('Isdelete', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('ZerodepId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_index('tbl_insurancecompany', 'tbl_zerodep', ['InsuranceCompanyId'], unique=False)
    op.create_index('tbl_vehicle_make', 'tbl_zerodep', ['Make_ID'], unique=False)
    op.create_table('tbl_zerodepforsegmentwise',
    sa.Column('ZerodepId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('InsuranceCompanyId', sa.Integer(), nullable=True),
    sa.Column('Make_ID', sa.Integer(), nullable=True),
    sa.Column('Model_Id', sa.Integer(), nullable=True),
    sa.Column('FuelTypeId', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('Age', sa.String(length=255), nullable=True),
    sa.Column('NillDep', sa.Double(), nullable=True),
    sa.Column('SecurePlus', sa.Double(), nullable=True),
    sa.Column('SPremium', sa.Double(), nullable=True),
    sa.Column('NO', sa.Integer(), nullable=True),
    sa.Column('Isdelete', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('ZerodepId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('tbl_zerodepnewaddonrate',
    sa.Column('AddOnId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Model_ID', sa.Integer(), nullable=True),
    sa.Column('MakeID', sa.Integer(), nullable=True),
    sa.Column('InsuranceCompanyId', sa.Integer(), nullable=True),
    sa.Column('Decline', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('Fueltypeid', sa.Integer(), nullable=True),
    sa.Column('BusinessTypeId', sa.Integer(), nullable=True),
    sa.Column('NCB', sa.String(length=255), nullable=True),
    sa.Column('ClusterId', sa.Integer(), nullable=True),
    sa.Column('Breaking', sa.String(length=255), nullable=True),
    sa.Column('PRVDetails', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('NillDep', sa.String(length=255), nullable=True),
    sa.Column('SecurePlus', sa.String(length=255), nullable=True),
    sa.Column('SPremium', sa.String(length=255), nullable=True),
    sa.Column('NO', sa.String(length=255), nullable=True),
    sa.Column('Isdelete', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('AddOnId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_zerodepnewaddonrate')
    op.drop_table('tbl_zerodepforsegmentwise')
    op.drop_index('tbl_vehicle_make', table_name='tbl_zerodep')
    op.drop_index('tbl_insurancecompany', table_name='tbl_zerodep')
    op.drop_table('tbl_zerodep')
    op.drop_table('tbl_selfdiscount')
    op.drop_table('tbl_quotation_prefix')
    op.drop_table('tbl_quot_liabilitypremium')
    op.drop_table('tbl_quot_damagepremium')
    op.drop_table('tbl_patoownerdriver')
    op.drop_table('tbl_insurancecompanywisetowingchanges')
    op.drop_table('tbl_insurancecompanyquotation')
    op.drop_table('tbl_insurancecompanybyvehicletype')
    op.drop_index('tbl_vehicle_model', table_name='tbl_appoddiscount')
    op.drop_index('tbl_vehicle_make', table_name='tbl_appoddiscount')
    op.drop_index('tbl_insurancecompany', table_name='tbl_appoddiscount')
    op.drop_table('tbl_appoddiscount')
    op.drop_table('tbl_app_twowheelercc_rate')
    op.drop_table('tbl_app_threewheeler_cc_rate')
    op.drop_table('tbl_app_requestedquotationfile')
    op.drop_table('tbl_app_quotationrequest')
    op.drop_table('tbl_app_quotationremark')
    op.drop_index('Title', table_name='tbl_app_quatationentry', mysql_length=200)
    op.drop_table('tbl_app_quatationentry')
    op.drop_table('tbl_app_pcv_cc_rate')
    op.drop_table('tbl_app_oddiscountnew_gcv')
    op.drop_table('tbl_app_oddiscountnew')
    op.drop_table('tbl_app_bus_cc_rate')
    op.drop_table('tbl_addonextraamt')
    # ### end Alembic commands ###
