"""create_phase4b_master_tables

Revision ID: cfb1bd63a8ff
Revises: 56635abf39f0
Create Date: 2026-10-05 09:56:07.520785+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb1bd63a8ff'
down_revision: Union[str, None] = '56635abf39f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_insurancecompany',
    sa.Column('InsuranceCompanyId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('InsuranceCompany', sa.String(length=255), nullable=True),
    sa.Column('BranchName', sa.String(length=255), nullable=True),
    sa.Column('BranchCode', sa.String(length=255), nullable=True),
    sa.Column('NCB', sa.String(length=255), nullable=False),
    sa.Column('Cluster', sa.String(length=255), nullable=False),
    sa.Column('ZeroDeep', sa.String(length=255), nullable=False),
    sa.Column('isdeleted', sa.String(length=255), nullable=True),
    sa.Column('IsAppQuotation', sa.String(length=255), nullable=False),
    sa.Column('MailId', sa.String(length=300), nullable=True),
    sa.Column('CompImgPath', sa.String(length=255), nullable=False),
    sa.Column('LedgerMId', sa.Integer(), nullable=False),
    sa.Column('ShortName', sa.String(length=255), nullable=False),
    sa.Column('CreditDays', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('PolicyNo', sa.String(length=500), nullable=False),
    sa.Column('len', sa.Integer(), nullable=False),
    sa.Column('InsurerSAIBA', sa.String(length=200), server_default=sa.text("'0'"), nullable=True),
    sa.Column('InsurerBranchAutoCodeSAIBA', sa.Text(), nullable=True),
    sa.Column('PE_CompanyName', sa.String(length=100), server_default=sa.text("'-'"), nullable=True),
    sa.Column('VantageInsurance', sa.String(length=200), server_default=sa.text("'0'"), nullable=True),
    sa.Column('VantageBranch', sa.String(length=100), server_default=sa.text("'0'"), nullable=True),
    sa.Column('VantageBranchAddress', sa.String(length=300), server_default=sa.text("'0'"), nullable=True),
    sa.PrimaryKeyConstraint('InsuranceCompanyId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('tbl_rto',
    sa.Column('RTOId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RTOLocation', sa.String(length=255), nullable=False),
    sa.Column('District', sa.String(length=255), nullable=False),
    sa.Column('REG_code', sa.String(length=255), nullable=True),
    sa.Column('State_ID_FK', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=255), nullable=True),
    sa.Column('ClusterId', sa.Integer(), nullable=False),
    sa.Column('isdeleted', sa.Integer(), nullable=True),
    sa.Column('StateId', sa.Integer(), nullable=True),
    sa.Column('RTOWithLocation', sa.String(length=100), server_default=sa.text("'0'"), nullable=True),
    sa.PrimaryKeyConstraint('RTOId'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('tbl_vehicle_make',
    sa.Column('Make_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Make_Name', sa.String(length=255), nullable=True),
    sa.Column('R_Make_ID', sa.Integer(), nullable=True),
    sa.Column('GCV', sa.String(length=255), nullable=True),
    sa.Column('Misc_D', sa.String(length=255), nullable=True),
    sa.Column('PCV', sa.String(length=255), nullable=True),
    sa.Column('PvtCar', sa.String(length=255), nullable=True),
    sa.Column('Two_Wheeler', sa.String(length=255), nullable=True),
    sa.Column('Bus', sa.String(length=255), nullable=True),
    sa.Column('Three_Wheeler', sa.String(length=255), nullable=True),
    sa.Column('Three_Wheeler_Pcv', sa.String(length=255), nullable=True),
    sa.Column('isdeleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('Make_ID'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('tbl_vehicle_model',
    sa.Column('Model_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Make_ID', sa.Integer(), nullable=True),
    sa.Column('Model_Name', sa.String(length=255), nullable=True),
    sa.Column('R_Make_ID', sa.Integer(), nullable=True),
    sa.Column('Type', sa.Integer(), nullable=True),
    sa.Column('SegmentId', sa.Integer(), nullable=False),
    sa.Column('isdeleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('Model_ID'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('tbl_Vehicle_Make', 'tbl_vehicle_model', ['Make_ID'], unique=False)
    op.create_table('tbl_vehicle_sub_type',
    sa.Column('Veh_Sub_Type_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Veh_Sub_Type_Name', sa.String(length=255), nullable=True),
    sa.Column('Veh_Type_ID', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Veh_Sub_Type_ID'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('tbl_Vehicle_Type', 'tbl_vehicle_sub_type', ['Veh_Type_ID'], unique=False)
    op.create_table('tbl_vehicle_type',
    sa.Column('Veh_Type_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Veh_Type_Name', sa.String(length=255), nullable=True),
    sa.Column('IsAppQuotation', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('PolicyTypeSAIBA', sa.String(length=200), server_default=sa.text("'0'"), nullable=True),
    sa.Column('VantagePolicyType', sa.String(length=200), server_default=sa.text("'0'"), nullable=True),
    sa.Column('Comprehensive', sa.String(length=200), nullable=True),
    sa.Column('TP', sa.String(length=200), nullable=True),
    sa.Column('Saod', sa.String(length=200), nullable=True),
    sa.Column('VehicleType', sa.String(length=200), nullable=True),
    sa.Column('NatureOfUse', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('Veh_Type_ID'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('tbl_vehicle_variants',
    sa.Column('Variant_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Veh_Type_ID', sa.Integer(), nullable=True),
    sa.Column('Veh_Sub_Type_ID', sa.Integer(), nullable=True),
    sa.Column('Model_ID', sa.Integer(), nullable=True),
    sa.Column('Make_Tac_Code', sa.String(length=255), nullable=True),
    sa.Column('Model_Tac_Code', sa.String(length=255), nullable=True),
    sa.Column('Variance', sa.String(length=255), nullable=True),
    sa.Column('Tac_Code', sa.String(length=255), nullable=True),
    sa.Column('Wheels', sa.String(length=255), nullable=True),
    sa.Column('Manufacturing_Year', sa.String(length=255), nullable=True),
    sa.Column('Operated_By', sa.String(length=255), nullable=True),
    sa.Column('Amp', sa.String(length=255), nullable=True),
    sa.Column('CC', sa.String(length=255), nullable=True),
    sa.Column('Unit_Name', sa.String(length=255), nullable=True),
    sa.Column('Battery_Manufacturer', sa.String(length=255), nullable=True),
    sa.Column('Gross_Weight', sa.String(length=255), nullable=True),
    sa.Column('Seating_Capacity', sa.String(length=255), nullable=True),
    sa.Column('Carrying_Capacity', sa.String(length=255), nullable=True),
    sa.Column('Body_Type', sa.String(length=255), nullable=True),
    sa.Column('Min_Seating_Capacity', sa.String(length=255), nullable=True),
    sa.Column('Max_Seating_Capacity', sa.String(length=255), nullable=True),
    sa.Column('Min_carrying_Capacity', sa.String(length=255), nullable=True),
    sa.Column('Max_carrying_Capacity', sa.String(length=255), nullable=True),
    sa.Column('Is_In_Black_Listed', sa.String(length=255), nullable=True),
    sa.Column('IsObsolete', sa.String(length=255), nullable=True),
    sa.Column('IsImported', sa.String(length=255), nullable=True),
    sa.Column('Vehicle_Segment_Name', sa.String(length=255), nullable=True),
    sa.Column('COM_Segment', sa.String(length=255), nullable=True),
    sa.Column('ExMumbai_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExMumbai_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExMumbai_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExNewDelhi_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExNewDelhi_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExNewDelhi_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExBangalore_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExBangalore_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExBangalore_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExKolkatta_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExKolkatta_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExKolkatta_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExAhmedabad_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExAhmedabad_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExAhmedabad_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExChandigarh_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExChandigarh_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExChandigarh_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExShimla_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExShimla_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExShimla_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExFaridabad_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExFaridabad_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExFaridabad_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExLucknow_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExLucknow_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExLucknow_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExDehradun_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExDehradun_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExDehradun_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExKohima_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExKohima_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExKohima_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExPatna_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExPatna_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExPatna_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExChennai_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExChennai_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExChennai_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExThiruvananthapuram_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExThiruvananthapuram_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExThiruvananthapuram_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExHyderabad_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExHyderabad_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExHyderabad_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExBhopal_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExBhopal_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExBhopal_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExRaipur_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExRaipur_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExRaipur_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExJaipur_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExJaipur_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExJaipur_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('ExPanaji_Body_Price', sa.String(length=255), nullable=True),
    sa.Column('ExPanaji_Model_Price', sa.String(length=255), nullable=True),
    sa.Column('ExPanaji_Chasis_Price', sa.String(length=255), nullable=True),
    sa.Column('Last_Updated_Date', sa.String(length=255), nullable=True),
    sa.Column('Mfg_BuildIn', sa.String(length=255), nullable=True),
    sa.Column('ModelStatus', sa.String(length=255), nullable=True),
    sa.Column('R_Make_ID', sa.Integer(), nullable=True),
    sa.Column('R_Model_ID', sa.Integer(), nullable=True),
    sa.Column('Make_Id', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('Variant_ID'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('tbl_Vehicle_Model', 'tbl_vehicle_variants', ['Model_ID'], unique=False)
    op.create_index('tbl_vehicle_sub_type', 'tbl_vehicle_variants', ['Veh_Sub_Type_ID'], unique=False)
    op.create_index('tbl_vehicle_type', 'tbl_vehicle_variants', ['Veh_Type_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tbl_vehicle_type', table_name='tbl_vehicle_variants')
    op.drop_index('tbl_vehicle_sub_type', table_name='tbl_vehicle_variants')
    op.drop_index('tbl_Vehicle_Model', table_name='tbl_vehicle_variants')
    op.drop_table('tbl_vehicle_variants')
    op.drop_table('tbl_vehicle_type')
    op.drop_index('tbl_Vehicle_Type', table_name='tbl_vehicle_sub_type')
    op.drop_table('tbl_vehicle_sub_type')
    op.drop_index('tbl_Vehicle_Make', table_name='tbl_vehicle_model')
    op.drop_table('tbl_vehicle_model')
    op.drop_table('tbl_vehicle_make')
    op.drop_table('tbl_rto')
    op.drop_table('tbl_insurancecompany')
    # ### end Alembic commands ###
