from decimal import Decimal
from datetime import datetime, date
from typing import Optional
from sqlalchemy import Integer, String, Text, DateTime, Date, Double, Index
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base


class Transaction(Base):
    """
    Issued Policy & Transaction Master Model (166 Verified Physical Columns)
    Physical Table: tbl_transaction
    Physical PK: TransanctionId
    Verified Column Count: 166
    Physical Foreign Keys: 0 (Enforced at application layer)
    """
    __tablename__ = "tbl_transaction"
    __table_args__ = {
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_general_ci",
        "mysql_row_format": "DYNAMIC",
    }

    TransanctionId: Mapped[int] = mapped_column("TransanctionId", Integer, primary_key=True, autoincrement=True)
    InwardNo: Mapped[Optional[str]] = mapped_column("InwardNo", String(255), nullable=True)
    TransDate: Mapped[Optional[datetime]] = mapped_column("TransDate", DateTime, nullable=True)
    BranchId: Mapped[Optional[int]] = mapped_column("BranchId", Integer, nullable=True)
    PolicyTypeId: Mapped[Optional[int]] = mapped_column("PolicyTypeId", Integer, nullable=True)
    CustomerId: Mapped[Optional[int]] = mapped_column("CustomerId", Integer, nullable=True)
    CustVehId: Mapped[Optional[int]] = mapped_column("CustVehId", Integer, nullable=True)
    InsuranceCompanyId: Mapped[Optional[int]] = mapped_column("InsuranceCompanyId", Integer, nullable=True)
    PolicyNo: Mapped[Optional[str]] = mapped_column("PolicyNo", String(255), nullable=True)
    CnIssueDate: Mapped[Optional[datetime]] = mapped_column("CnIssueDate", DateTime, nullable=True)
    PolicyModeId: Mapped[Optional[int]] = mapped_column("PolicyModeId", Integer, nullable=True)
    Lead_No: Mapped[Optional[str]] = mapped_column("Lead_No", String(255), nullable=True)
    ProductTypeId: Mapped[Optional[int]] = mapped_column("ProductTypeId", Integer, nullable=True)
    BusinessTypeId: Mapped[Optional[int]] = mapped_column("BusinessTypeId", Integer, nullable=True)
    AgentId: Mapped[Optional[int]] = mapped_column("AgentId", Integer, nullable=True)
    SalesEx_id: Mapped[Optional[int]] = mapped_column("SalesEx_id", Integer, nullable=True)
    RiskStartdate: Mapped[Optional[datetime]] = mapped_column("RiskStartdate", DateTime, nullable=True)
    ExpiryDate: Mapped[Optional[datetime]] = mapped_column("ExpiryDate", DateTime, nullable=True)
    SumInsured: Mapped[Optional[Decimal]] = mapped_column("SumInsured", Double(asdecimal=True), nullable=True)
    GVW: Mapped[Optional[str]] = mapped_column("GVW", String(255), nullable=True)
    Imt23: Mapped[Optional[str]] = mapped_column("Imt23", String(255), nullable=True)
    IMT47: Mapped[Optional[str]] = mapped_column("IMT47", String(255), nullable=True)
    AddOn: Mapped[Optional[str]] = mapped_column("AddOn", String(255), nullable=True)
    TowingChargesAmt: Mapped[Optional[Decimal]] = mapped_column("TowingChargesAmt", Double(asdecimal=True), nullable=True)
    NCB: Mapped[Optional[Decimal]] = mapped_column("NCB", Double(asdecimal=True), nullable=True)
    NCBPermium: Mapped[Optional[Decimal]] = mapped_column("NCBPermium", Double(asdecimal=True), nullable=True)
    ODDiscount: Mapped[Optional[Decimal]] = mapped_column("ODDiscount", Double(asdecimal=True), nullable=True)
    ODPermium: Mapped[Optional[Decimal]] = mapped_column("ODPermium", Double(asdecimal=True), nullable=True)
    TPPermium: Mapped[Optional[Decimal]] = mapped_column("TPPermium", Double(asdecimal=True), nullable=True)
    NetPermium: Mapped[Optional[Decimal]] = mapped_column("NetPermium", Double(asdecimal=True), nullable=True)
    ProPosalAmt: Mapped[Optional[Decimal]] = mapped_column("ProPosalAmt", Double(asdecimal=True), nullable=True)
    Remark: Mapped[Optional[str]] = mapped_column("Remark", String(255), nullable=True)
    ReferenceType: Mapped[Optional[str]] = mapped_column("ReferenceType", String(255), nullable=True)
    ReferenceBy: Mapped[Optional[str]] = mapped_column("ReferenceBy", String(255), nullable=True)
    ReferenceRole: Mapped[Optional[str]] = mapped_column("ReferenceRole", String(255), nullable=True)
    PersonName: Mapped[Optional[str]] = mapped_column("PersonName", String(255), nullable=True)
    Tat: Mapped[Optional[str]] = mapped_column("Tat", String(255), nullable=True)
    AgentComm: Mapped[Optional[Decimal]] = mapped_column("AgentComm", Double(asdecimal=True), nullable=True)
    AgentCommAmt: Mapped[Optional[Decimal]] = mapped_column("AgentCommAmt", Double(asdecimal=True), nullable=True)
    TdsAmt: Mapped[Optional[Decimal]] = mapped_column("TdsAmt", Double(asdecimal=True), nullable=True)
    NetCommission: Mapped[Optional[Decimal]] = mapped_column("NetCommission", Double(asdecimal=True), nullable=True)
    Amount: Mapped[Optional[Decimal]] = mapped_column("Amount", Double(asdecimal=True), nullable=True)
    TStatus: Mapped[Optional[str]] = mapped_column("TStatus", String(255), nullable=True)
    PaidAmount: Mapped[Optional[Decimal]] = mapped_column("PaidAmount", Double(asdecimal=True), nullable=True)
    OutstandingAmount: Mapped[Optional[Decimal]] = mapped_column("OutstandingAmount", Double(asdecimal=True), nullable=True)
    CommissionPaid: Mapped[Optional[int]] = mapped_column("CommissionPaid", Integer, nullable=True)
    pendingStatus: Mapped[Optional[int]] = mapped_column("pendingStatus", Integer, nullable=True)
    QuatationCode: Mapped[Optional[str]] = mapped_column("QuatationCode", String(255), nullable=True)
    isdeleted: Mapped[Optional[str]] = mapped_column("isdeleted", String(255), nullable=True)
    CreateDate: Mapped[Optional[datetime]] = mapped_column("CreateDate", DateTime, nullable=True)
    CreateUser: Mapped[Optional[str]] = mapped_column("CreateUser", String(255), nullable=True)
    UpdateDate: Mapped[Optional[datetime]] = mapped_column("UpdateDate", DateTime, nullable=True)
    UpdateUser: Mapped[Optional[str]] = mapped_column("UpdateUser", String(255), nullable=True)
    Tat_OD: Mapped[Optional[str]] = mapped_column("Tat_OD", String(255), nullable=True)
    AgentComm_OD: Mapped[Optional[Decimal]] = mapped_column("AgentComm_OD", Double(asdecimal=True), nullable=True)
    AgentCommAmt_OD: Mapped[Optional[Decimal]] = mapped_column("AgentCommAmt_OD", Double(asdecimal=True), nullable=True)
    TdsAmt_OD: Mapped[Optional[Decimal]] = mapped_column("TdsAmt_OD", Double(asdecimal=True), nullable=True)
    NetCommission_OD: Mapped[Optional[Decimal]] = mapped_column("NetCommission_OD", Double(asdecimal=True), nullable=True)
    Tat_Net: Mapped[Optional[str]] = mapped_column("Tat_Net", String(255), nullable=True)
    AgentComm_Net: Mapped[Optional[Decimal]] = mapped_column("AgentComm_Net", Double(asdecimal=True), nullable=True)
    AgentCommAmt_Net: Mapped[Optional[Decimal]] = mapped_column("AgentCommAmt_Net", Double(asdecimal=True), nullable=True)
    TdsAmt_Net: Mapped[Optional[Decimal]] = mapped_column("TdsAmt_Net", Double(asdecimal=True), nullable=True)
    NetCommission_Net: Mapped[Optional[Decimal]] = mapped_column("NetCommission_Net", Double(asdecimal=True), nullable=True)
    AgentComm_Extra: Mapped[Optional[Decimal]] = mapped_column("AgentComm_Extra", Double(asdecimal=True), nullable=True)
    AgentCommAmt_Extra: Mapped[Optional[Decimal]] = mapped_column("AgentCommAmt_Extra", Double(asdecimal=True), nullable=True)
    TdsAmt_Extra: Mapped[Optional[Decimal]] = mapped_column("TdsAmt_Extra", Double(asdecimal=True), nullable=True)
    NetCommission_Extra: Mapped[Optional[Decimal]] = mapped_column("NetCommission_Extra", Double(asdecimal=True), nullable=True)
    PACovertoOwner: Mapped[Decimal] = mapped_column("PACovertoOwner", Double(asdecimal=True), nullable=False)
    PACoverDriverCleaner: Mapped[Decimal] = mapped_column("PACoverDriverCleaner", Double(asdecimal=True), nullable=False)
    LegalLiabilitytoPaidDriver: Mapped[Decimal] = mapped_column("LegalLiabilitytoPaidDriver", Double(asdecimal=True), nullable=False)
    CommProcessSubmit: Mapped[Optional[int]] = mapped_column("CommProcessSubmit", Integer, nullable=True)
    IsRecalculate: Mapped[int] = mapped_column("IsRecalculate", Integer, nullable=False)
    MotorOrNonMotor: Mapped[str] = mapped_column("MotorOrNonMotor", String(255), nullable=False)
    InsuranceTypeId: Mapped[int] = mapped_column("InsuranceTypeId", Integer, nullable=False)
    InsuranceSubTypeId: Mapped[int] = mapped_column("InsuranceSubTypeId", Integer, nullable=False)
    TypeOfSubType: Mapped[int] = mapped_column("TypeOfSubType", Integer, nullable=False)
    AddOnRate: Mapped[Decimal] = mapped_column("AddOnRate", Double(asdecimal=True), nullable=False)
    OnlinePaymentToCompany: Mapped[int] = mapped_column("OnlinePaymentToCompany", Integer, nullable=False)
    GridAgentId: Mapped[int] = mapped_column("GridAgentId", Integer, nullable=False)
    PaymentDocNo: Mapped[Optional[str]] = mapped_column("PaymentDocNo", String(255), nullable=True)
    CompSubmitionDocNo: Mapped[Optional[str]] = mapped_column("CompSubmitionDocNo", String(255), nullable=True)
    PremiumCashToBank: Mapped[int] = mapped_column("PremiumCashToBank", Integer, nullable=False)
    PremiumCashDocNo: Mapped[Optional[str]] = mapped_column("PremiumCashDocNo", String(255), nullable=True)
    PolicyPrefix: Mapped[Optional[str]] = mapped_column("PolicyPrefix", String(255), nullable=True)
    CreatedSystem: Mapped[str] = mapped_column("CreatedSystem", String(255), nullable=False)
    CreatedIP: Mapped[str] = mapped_column("CreatedIP", String(255), nullable=False)
    UpdatedSystem: Mapped[str] = mapped_column("UpdatedSystem", String(255), nullable=False)
    UpdatedIP: Mapped[str] = mapped_column("UpdatedIP", String(255), nullable=False)
    PortalId: Mapped[str] = mapped_column("PortalId", String(255), nullable=False)
    PaymentBy: Mapped[Optional[str]] = mapped_column("PaymentBy", String(255), nullable=True)
    GridValidDate: Mapped[Optional[datetime]] = mapped_column("GridValidDate", DateTime, nullable=True)
    FranchiseCode: Mapped[str] = mapped_column("FranchiseCode", String(255), nullable=False)
    SelfDiscount: Mapped[Decimal] = mapped_column("SelfDiscount", Double(asdecimal=True), nullable=False)
    IntensiveAmount: Mapped[Decimal] = mapped_column("IntensiveAmount", Double(asdecimal=True), nullable=False)
    LocationHeadId: Mapped[int] = mapped_column("LocationHeadId", Integer, nullable=False)
    Ischequeclearing: Mapped[int] = mapped_column("Ischequeclearing", Integer, nullable=False)
    CompanyChequeNo: Mapped[Optional[str]] = mapped_column("CompanyChequeNo", String(255), nullable=True)
    IsChequeCleared: Mapped[int] = mapped_column("IsChequeCleared", Integer, nullable=False)
    IsCompanyChequeNo: Mapped[int] = mapped_column("IsCompanyChequeNo", Integer, nullable=False)
    IsActivePendingCash: Mapped[int] = mapped_column("IsActivePendingCash", Integer, nullable=False)
    tdsPercent: Mapped[Decimal] = mapped_column("tdsPercent", Double(asdecimal=True), nullable=False)
    FinancialYear: Mapped[str] = mapped_column("FinancialYear", String(255), nullable=False)
    PaymentDate: Mapped[Optional[datetime]] = mapped_column("PaymentDate", DateTime, nullable=True)
    OnlineToCompanyDate: Mapped[Optional[datetime]] = mapped_column("OnlineToCompanyDate", DateTime, nullable=True)
    CustDocStatus: Mapped[Optional[str]] = mapped_column("CustDocStatus", String(255), nullable=True)
    CashBackStatus: Mapped[int] = mapped_column("CashBackStatus", Integer, nullable=False)
    CashBackAmt: Mapped[Decimal] = mapped_column("CashBackAmt", Double(asdecimal=True), nullable=False)
    CutNPay: Mapped[Decimal] = mapped_column("CutNPay", Double(asdecimal=True), nullable=False)
    ChequeBankStatus: Mapped[int] = mapped_column("ChequeBankStatus", Integer, nullable=False)
    CheqBankDate: Mapped[Optional[datetime]] = mapped_column("CheqBankDate", DateTime, nullable=True)
    IncentiveStatus: Mapped[int] = mapped_column("IncentiveStatus", Integer, nullable=False)
    IncentiveDoc_No: Mapped[Optional[str]] = mapped_column("IncentiveDoc_No", String(255), nullable=True)
    DeuDate: Mapped[datetime] = mapped_column("DeuDate", DateTime, nullable=False)
    UpdateEntryStatus: Mapped[int] = mapped_column("UpdateEntryStatus", Integer, nullable=False)
    UpdateEntryRemark: Mapped[Optional[str]] = mapped_column("UpdateEntryRemark", String(255), nullable=True)
    ExectiveGrid: Mapped[Decimal] = mapped_column("ExectiveGrid", Double(asdecimal=True), nullable=False)
    EWalletAmountUsed: Mapped[Decimal] = mapped_column("EWalletAmountUsed", Double(asdecimal=True), nullable=False)
    PolicycancelId: Mapped[int] = mapped_column("PolicycancelId", Integer, nullable=False)
    Hie_DataSales: Mapped[Optional[str]] = mapped_column("Hie_DataSales", String(500), nullable=True)
    Hie_DataOprn: Mapped[Optional[str]] = mapped_column("Hie_DataOprn", String(500), nullable=True)
    FranchiseCommPaid: Mapped[int] = mapped_column("FranchiseCommPaid", Integer, nullable=False)
    FranchisePaymentDocNo: Mapped[Optional[str]] = mapped_column("FranchisePaymentDocNo", String(255), nullable=True)
    IsRconDataMatch: Mapped[int] = mapped_column("IsRconDataMatch", Integer, nullable=False)
    accounting_period: Mapped[Optional[datetime]] = mapped_column("accounting_period", DateTime, nullable=True)
    TransId: Mapped[int] = mapped_column("TransId", Integer, nullable=False)
    RconGrid: Mapped[Decimal] = mapped_column("RconGrid", Double(asdecimal=True), nullable=False)
    RconComm: Mapped[Decimal] = mapped_column("RconComm", Double(asdecimal=True), nullable=False)
    IsQualityCheck: Mapped[int] = mapped_column("IsQualityCheck", Integer, nullable=False)
    QualityCheckDate: Mapped[datetime] = mapped_column("QualityCheckDate", DateTime, nullable=False)
    CorrectionText: Mapped[Optional[str]] = mapped_column("CorrectionText", String(300), nullable=True)
    ND: Mapped[str] = mapped_column("ND", String(100), nullable=False)
    FranchiseTypeId: Mapped[int] = mapped_column("FranchiseTypeId", Integer, nullable=False)
    T_Grid: Mapped[Optional[Decimal]] = mapped_column("T_Grid", Double(asdecimal=True), nullable=True)
    T_Tds: Mapped[Optional[Decimal]] = mapped_column("T_Tds", Double(asdecimal=True), nullable=True)
    T_Net: Mapped[Optional[Decimal]] = mapped_column("T_Net", Double(asdecimal=True), nullable=True)
    F_Grid: Mapped[Optional[Decimal]] = mapped_column("F_Grid", Double(asdecimal=True), nullable=True)
    F_Tds: Mapped[Optional[Decimal]] = mapped_column("F_Tds", Double(asdecimal=True), nullable=True)
    F_Net: Mapped[Optional[Decimal]] = mapped_column("F_Net", Double(asdecimal=True), nullable=True)
    M_Grid: Mapped[Optional[Decimal]] = mapped_column("M_Grid", Double(asdecimal=True), nullable=True)
    M_Tds: Mapped[Optional[Decimal]] = mapped_column("M_Tds", Double(asdecimal=True), nullable=True)
    M_Net: Mapped[Optional[Decimal]] = mapped_column("M_Net", Double(asdecimal=True), nullable=True)
    IMDBroker: Mapped[Optional[str]] = mapped_column("IMDBroker", String(100), nullable=True)
    PrevYearCompanyId: Mapped[Optional[int]] = mapped_column("PrevYearCompanyId", Integer, nullable=True)
    GridId: Mapped[Optional[int]] = mapped_column("GridId", Integer, nullable=True)
    BrokerGridId: Mapped[Optional[int]] = mapped_column("BrokerGridId", Integer, nullable=True)
    NCBPer: Mapped[Optional[Decimal]] = mapped_column("NCBPer", Double(asdecimal=True), nullable=True)
    MISId: Mapped[Optional[int]] = mapped_column("MISId", Integer, nullable=True)
    PaymentRequest: Mapped[Optional[str]] = mapped_column("PaymentRequest", String(150), nullable=True)
    POSPType_Id: Mapped[Optional[int]] = mapped_column("POSPType_Id", Integer, nullable=True)
    POSP_Id: Mapped[Optional[int]] = mapped_column("POSP_Id", Integer, nullable=True)
    RAPaymentStatus: Mapped[str] = mapped_column("RAPaymentStatus", String(100), nullable=False)
    PaymentDetails1: Mapped[Optional[str]] = mapped_column("PaymentDetails1", String(100), nullable=True)
    PaymentDetails2: Mapped[Optional[str]] = mapped_column("PaymentDetails2", String(100), nullable=True)
    GST_Amount: Mapped[Optional[Decimal]] = mapped_column("GST_Amount", Double(asdecimal=True), nullable=True)
    IsProcess: Mapped[Optional[int]] = mapped_column("IsProcess", Integer, nullable=True)
    ProcessDate: Mapped[Optional[datetime]] = mapped_column("ProcessDate", DateTime, nullable=True)
    ProcessBy: Mapped[Optional[str]] = mapped_column("ProcessBy", String(100), nullable=True)
    IB_Doc_No: Mapped[Optional[int]] = mapped_column("IB_Doc_No", Integer, nullable=True)
    IB_PaymentDate: Mapped[Optional[datetime]] = mapped_column("IB_PaymentDate", DateTime, nullable=True)
    IB_ReceiptStatus: Mapped[Optional[int]] = mapped_column("IB_ReceiptStatus", Integer, nullable=True)
    IB_PaymentBy: Mapped[Optional[str]] = mapped_column("IB_PaymentBy", String(100), nullable=True)
    Slab: Mapped[Optional[str]] = mapped_column("Slab", String(100), nullable=True)
    calliber_policyId: Mapped[Optional[int]] = mapped_column("calliber_policyId", Integer, nullable=True)
    calliber_UpdateBy: Mapped[Optional[str]] = mapped_column("calliber_UpdateBy", String(200), nullable=True)
    RoadSidePremium: Mapped[Optional[Decimal]] = mapped_column("RoadSidePremium", Double(asdecimal=True), nullable=True)
    PolicyId: Mapped[Optional[str]] = mapped_column("PolicyId", String(200), nullable=True)
