from decimal import Decimal
from datetime import datetime, date
from typing import Optional
from sqlalchemy import Integer, String, Text, DateTime, Date, Double, Index
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base


class TransactionAppNew(Base):
    """
    Mobile / Partner Proposal Intake Staging Model
    Physical Table: tbl_transactionappnew
    Physical PK: TransId
    Verified Column Count: 116
    Physical Foreign Keys: 0 (Enforced at application layer)
    """
    __tablename__ = "tbl_transactionappnew"
    __table_args__ = {
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_general_ci",
        "mysql_row_format": "DYNAMIC",
    }

    TransId: Mapped[int] = mapped_column("TransId", Integer, primary_key=True, autoincrement=True)
    TransDate: Mapped[Optional[datetime]] = mapped_column("TransDate", DateTime, nullable=True)
    OtherAgentName: Mapped[Optional[str]] = mapped_column("OtherAgentName", String(255), nullable=True)
    insurancecompany: Mapped[Optional[str]] = mapped_column("insurancecompany", String(255), nullable=True)
    ProductType: Mapped[Optional[str]] = mapped_column("ProductType", String(255), nullable=True)
    BusinessType: Mapped[Optional[str]] = mapped_column("BusinessType", String(255), nullable=True)
    PolicyMode: Mapped[Optional[str]] = mapped_column("PolicyMode", String(255), nullable=True)
    UserId: Mapped[Optional[int]] = mapped_column("UserId", Integer, nullable=True)
    SalesExecutiveId: Mapped[Optional[int]] = mapped_column("SalesExecutiveId", Integer, nullable=True)
    FranchaiseId: Mapped[Optional[int]] = mapped_column("FranchaiseId", Integer, nullable=True)
    Initial: Mapped[Optional[str]] = mapped_column("Initial", String(255), nullable=True)
    Name: Mapped[Optional[str]] = mapped_column("Name", String(2000), nullable=True)
    CustMName: Mapped[Optional[str]] = mapped_column("CustMName", String(255), nullable=True)
    CustLName: Mapped[Optional[str]] = mapped_column("CustLName", String(255), nullable=True)
    Gender: Mapped[Optional[str]] = mapped_column("Gender", String(255), nullable=True)
    State: Mapped[Optional[str]] = mapped_column("State", String(255), nullable=True)
    District: Mapped[Optional[str]] = mapped_column("District", String(255), nullable=True)
    PinCode: Mapped[Optional[str]] = mapped_column("PinCode", String(255), nullable=True)
    ContactNo: Mapped[Optional[str]] = mapped_column("ContactNo", String(255), nullable=True)
    ContactNo2: Mapped[Optional[str]] = mapped_column("ContactNo2", String(255), nullable=True)
    Emailid: Mapped[Optional[str]] = mapped_column("Emailid", String(255), nullable=True)
    Nomineename: Mapped[Optional[str]] = mapped_column("Nomineename", String(255), nullable=True)
    VehicleType: Mapped[Optional[str]] = mapped_column("VehicleType", String(255), nullable=True)
    Vehiclesubtype: Mapped[Optional[str]] = mapped_column("Vehiclesubtype", String(255), nullable=True)
    VehicleMake: Mapped[Optional[str]] = mapped_column("VehicleMake", String(255), nullable=True)
    VehicleModel: Mapped[Optional[str]] = mapped_column("VehicleModel", String(255), nullable=True)
    VehicleVariance: Mapped[Optional[str]] = mapped_column("VehicleVariance", String(255), nullable=True)
    FuelTypeId: Mapped[Optional[str]] = mapped_column("FuelTypeId", String(255), nullable=True)
    MfgDate: Mapped[Optional[datetime]] = mapped_column("MfgDate", DateTime, nullable=True)
    SeatsCapacity: Mapped[Optional[str]] = mapped_column("SeatsCapacity", String(255), nullable=True)
    Hypothecation: Mapped[Optional[str]] = mapped_column("Hypothecation", String(255), nullable=True)
    GrossVehicleWeightCC: Mapped[Optional[str]] = mapped_column("GrossVehicleWeightCC", String(255), nullable=True)
    StartDate: Mapped[Optional[date]] = mapped_column("StartDate", Date, nullable=True)
    Expirydate: Mapped[Optional[date]] = mapped_column("Expirydate", Date, nullable=True)
    LeadNo: Mapped[Optional[str]] = mapped_column("LeadNo", String(255), nullable=True)
    ODDiscount: Mapped[Optional[Decimal]] = mapped_column("ODDiscount", Double(asdecimal=True), nullable=True)
    NCB: Mapped[Optional[Decimal]] = mapped_column("NCB", Double(asdecimal=True), nullable=True)
    TPPremium: Mapped[Optional[Decimal]] = mapped_column("TPPremium", Double(asdecimal=True), nullable=True)
    ODPremium: Mapped[Optional[Decimal]] = mapped_column("ODPremium", Double(asdecimal=True), nullable=True)
    NetPremium: Mapped[Optional[Decimal]] = mapped_column("NetPremium", Double(asdecimal=True), nullable=True)
    Premium: Mapped[Optional[Decimal]] = mapped_column("Premium", Double(asdecimal=True), nullable=True)
    IDV: Mapped[Optional[str]] = mapped_column("IDV", String(255), nullable=True)
    PaymentMode: Mapped[Optional[str]] = mapped_column("PaymentMode", String(255), nullable=True)
    PaymentDetails1: Mapped[Optional[str]] = mapped_column("PaymentDetails1", String(255), nullable=True)
    PaymentDetails2: Mapped[Optional[str]] = mapped_column("PaymentDetails2", String(255), nullable=True)
    CoverStatus: Mapped[Optional[str]] = mapped_column("CoverStatus", String(255), nullable=True)
    IMT23: Mapped[Optional[str]] = mapped_column("IMT23", String(255), nullable=True)
    IMT47: Mapped[Optional[str]] = mapped_column("IMT47", String(255), nullable=True)
    ADDON: Mapped[Optional[str]] = mapped_column("ADDON", String(255), nullable=True)
    Document_List: Mapped[Optional[str]] = mapped_column("Document_List", String(255), nullable=True)
    RegistrationNo: Mapped[Optional[str]] = mapped_column("RegistrationNo", String(255), nullable=True)
    ReadStatus: Mapped[Optional[str]] = mapped_column("ReadStatus", String(255), nullable=True)
    policytype: Mapped[Optional[str]] = mapped_column("policytype", String(255), nullable=True)
    Note: Mapped[Optional[str]] = mapped_column("Note", String(255), nullable=True)
    QuatationCode: Mapped[Optional[str]] = mapped_column("QuatationCode", String(255), nullable=True)
    NCBPre: Mapped[Optional[Decimal]] = mapped_column("NCBPre", Double(asdecimal=True), nullable=True)
    FileUpload: Mapped[Optional[str]] = mapped_column("FileUpload", String(1000), nullable=True)
    Remark: Mapped[Optional[str]] = mapped_column("Remark", String(255), nullable=True)
    FileNameForPdf: Mapped[Optional[str]] = mapped_column("FileNameForPdf", String(255), nullable=True)
    Amount: Mapped[Optional[Decimal]] = mapped_column("Amount", Double(asdecimal=True), nullable=True)
    NEFTDate: Mapped[Optional[datetime]] = mapped_column("NEFTDate", DateTime, nullable=True)
    UserRoleId: Mapped[Optional[int]] = mapped_column("UserRoleId", Integer, nullable=True)
    IsOwnerApprove: Mapped[Optional[int]] = mapped_column("IsOwnerApprove", Integer, nullable=True)
    IsChashierApprove: Mapped[Optional[int]] = mapped_column("IsChashierApprove", Integer, nullable=True)
    FlagForPopup: Mapped[Optional[int]] = mapped_column("FlagForPopup", Integer, nullable=True)
    Quot_Type: Mapped[str] = mapped_column("Quot_Type", String(255), nullable=False)
    CashPaidAmt: Mapped[Decimal] = mapped_column("CashPaidAmt", Double(asdecimal=True), nullable=False)
    CashShortAmt: Mapped[Decimal] = mapped_column("CashShortAmt", Double(asdecimal=True), nullable=False)
    CashType: Mapped[Optional[str]] = mapped_column("CashType", String(255), nullable=True)
    UpdatedDate: Mapped[Optional[datetime]] = mapped_column("UpdatedDate", DateTime, nullable=True)
    UpdatedUser: Mapped[Optional[str]] = mapped_column("UpdatedUser", String(255), nullable=True)
    TransEmpId: Mapped[int] = mapped_column("TransEmpId", Integer, nullable=False)
    LocationHeadId: Mapped[int] = mapped_column("LocationHeadId", Integer, nullable=False)
    CoordinatorId: Mapped[int] = mapped_column("CoordinatorId", Integer, nullable=False)
    CashStatus: Mapped[str] = mapped_column("CashStatus", String(255), nullable=False)
    IsAccountApproval: Mapped[int] = mapped_column("IsAccountApproval", Integer, nullable=False)
    AccountRemark: Mapped[Optional[str]] = mapped_column("AccountRemark", String(255), nullable=True)
    ApprovedBy: Mapped[Optional[str]] = mapped_column("ApprovedBy", String(255), nullable=True)
    AppShortFallAmt: Mapped[Decimal] = mapped_column("AppShortFallAmt", Double(asdecimal=True), nullable=False)
    IsSubmit: Mapped[int] = mapped_column("IsSubmit", Integer, nullable=False)
    Grid: Mapped[Decimal] = mapped_column("Grid", Double(asdecimal=True), nullable=False)
    CashBackAmt: Mapped[Decimal] = mapped_column("CashBackAmt", Double(asdecimal=True), nullable=False)
    Paymentlink: Mapped[str] = mapped_column("Paymentlink", String(255), nullable=False)
    TDS: Mapped[Decimal] = mapped_column("TDS", Double(asdecimal=True), nullable=False)
    incentive: Mapped[Decimal] = mapped_column("incentive", Double(asdecimal=True), nullable=False)
    ICQuotationId: Mapped[Optional[int]] = mapped_column("ICQuotationId", Integer, nullable=True)
    RAPaymentStatus: Mapped[Optional[str]] = mapped_column("RAPaymentStatus", String(255), nullable=True)
    Urllink: Mapped[Optional[str]] = mapped_column("Urllink", String(1000), nullable=True)
    FranchiseCode: Mapped[str] = mapped_column("FranchiseCode", String(255), nullable=False)
    ExectiveGrid: Mapped[Decimal] = mapped_column("ExectiveGrid", Double(asdecimal=True), nullable=False)
    MgfYear: Mapped[str] = mapped_column("MgfYear", String(255), nullable=False)
    EWalletUsedamt: Mapped[Decimal] = mapped_column("EWalletUsedamt", Double(asdecimal=True), nullable=False)
    EwalletStatus: Mapped[int] = mapped_column("EwalletStatus", Integer, nullable=False)
    Hie_DataSales: Mapped[Optional[str]] = mapped_column("Hie_DataSales", String(500), nullable=True)
    Hie_DataOprn: Mapped[Optional[str]] = mapped_column("Hie_DataOprn", String(500), nullable=True)
    TPGrid: Mapped[Decimal] = mapped_column("TPGrid", Double(asdecimal=True), nullable=False)
    PremiumPaidDate: Mapped[Optional[datetime]] = mapped_column("PremiumPaidDate", DateTime, nullable=True)
    TPCommission: Mapped[Decimal] = mapped_column("TPCommission", Double(asdecimal=True), nullable=False)
    ODCommission: Mapped[Decimal] = mapped_column("ODCommission", Double(asdecimal=True), nullable=False)
    NETCommission: Mapped[Decimal] = mapped_column("NETCommission", Double(asdecimal=True), nullable=False)
    OutstandingAmt: Mapped[Decimal] = mapped_column("OutstandingAmt", Double(asdecimal=True), nullable=False)
    OutstandingWithPersonId: Mapped[int] = mapped_column("OutstandingWithPersonId", Integer, nullable=False)
    ReceivedAmtLedgerMId: Mapped[int] = mapped_column("ReceivedAmtLedgerMId", Integer, nullable=False)
    InsuranceTypeId: Mapped[int] = mapped_column("InsuranceTypeId", Integer, nullable=False)
    InsuranceSubTypeId: Mapped[int] = mapped_column("InsuranceSubTypeId", Integer, nullable=False)
    TypeofSubId: Mapped[int] = mapped_column("TypeofSubId", Integer, nullable=False)
    ND: Mapped[str] = mapped_column("ND", String(100), nullable=False)
    PrevYearCompanyId: Mapped[Optional[int]] = mapped_column("PrevYearCompanyId", Integer, nullable=True)
    GridId: Mapped[Optional[int]] = mapped_column("GridId", Integer, nullable=True)
    NCBPer: Mapped[Optional[Decimal]] = mapped_column("NCBPer", Double(asdecimal=True), nullable=True)
    ChequeApprovalBy: Mapped[Optional[str]] = mapped_column("ChequeApprovalBy", String(200), nullable=True)
    ChequeApprovalDate: Mapped[Optional[datetime]] = mapped_column("ChequeApprovalDate", DateTime, nullable=True)
    ChequeApprovalStatus: Mapped[int] = mapped_column("ChequeApprovalStatus", Integer, nullable=False)
    AppReqUser: Mapped[Optional[str]] = mapped_column("AppReqUser", String(500), nullable=True)
    CustType: Mapped[Optional[str]] = mapped_column("CustType", String(50), nullable=True)
    ClientId: Mapped[Optional[int]] = mapped_column("ClientId", Integer, nullable=True)
